# Generated by Django 4.2.3 on 2023-07-23 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_alter_comment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 8, 9, 26, 236524, tzinfo=datetime.timezone.utc), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='projects.task'),
        ),
    ]
