# Generated by Django 4.2.3 on 2023-07-23 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_comment_comment_date_alter_worker_worker_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.worker'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 13, 24, 53, 869188, tzinfo=datetime.timezone.utc), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.CharField(choices=[('новая', 'новая'), ('в работе', 'в работе'), ('закрыта', 'закрыта')], default='новая', max_length=8, verbose_name='статус'),
        ),
    ]
